In [4]:
# vetores
v = Int8[1,1.0,2,1000]
# erro por 1000 ser superior ao max de um Int8

InexactError: InexactError: trunc(Int8, 1000)

In [7]:
v = Int64[1,1.1,2,1000]
# erro devido ao float 1.1

InexactError: InexactError: Int64(1.1)

In [8]:
v = Int64[1,1.0,2,1000]
# deveria dar erro, mas como 1.0 é igual a 1 não dá
# neste caso deveria ser utilizado o tipo de dados Float64

4-element Array{Int64,1}:
    1
    1
    2
 1000

In [9]:
v = Float64[1,1.0,2,1000]

4-element Array{Float64,1}:
    1.0
    1.0
    2.0
 1000.0

In [12]:
v = [1,1.0,2,1000]

4-element Array{Float64,1}:
    1.0
    1.0
    2.0
 1000.0

In [13]:
v = collect(range(3, stop = 8))

6-element Array{Int64,1}:
 3
 4
 5
 6
 7
 8

In [14]:
v = collect(range(3, stop = 8, step = 2))

3-element Array{Int64,1}:
 3
 5
 7

In [17]:
v = collect(range(3, stop = 8, length = 6))

6-element Array{Float64,1}:
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0

In [20]:
# collect(init, step, stop)
w = collect(3:2:8)

3-element Array{Int64,1}:
 3
 5
 7

In [21]:
w = collect(3:8)

6-element Array{Int64,1}:
 3
 4
 5
 6
 7
 8

In [22]:
typeof(w)

Array{Int64,1}

In [23]:
typeof(3:2:8)

StepRange{Int64,Int64}

In [24]:
typeof(collect(3:2:8))

Array{Int64,1}

In [26]:
w = collect(3:8)
eltype(w)

Int64

In [61]:
Vector{Float64}(undef, 5)

5-element Array{Float64,1}:
 6.94149035582567e-310
 6.9414937346442e-310 
 6.9414937346347e-310 
 6.9414907308476e-310 
 6.94149073084283e-310

In [65]:
# array de uma dimensão
Array{Float64,1}(undef, 5)

5-element Array{Float64,1}:
 6.9414887219229e-310 
 6.9414887219245e-310 
 6.94148872192607e-310
 6.94148872192765e-310
 6.94148872192923e-310

In [64]:
# array de duas dimensões
Array{Float64,2}(undef, 5,5)

5×5 Array{Float64,2}:
 6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310
 6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310
 6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310
 6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310
 6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310  6.94149e-310

In [69]:
# adiconar vetores (atenção com a dimensão dos vetores)
t = [1, 2, 3]
d = [44,55,66]
z = t + d

3-element Array{Int64,1}:
 45
 57
 69

In [67]:
t = [1, 2, 3]
d = [44,55,66]
z = [t;d]

6-element Array{Int64,1}:
  1
  2
  3
 44
 55
 66

In [72]:
z = [d;t]

6-element Array{Int64,1}:
 44
 55
 66
  1
  2
  3

In [71]:
z = [t; 3; d; 1:3]

10-element Array{Int64,1}:
  1
  2
  3
  3
 44
 55
 66
  1
  2
  3

In [73]:
# criar um vetor só com zeros (tipo, quantidade)
zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [74]:
zeros(Int64,4)

4-element Array{Int64,1}:
 0
 0
 0
 0

In [75]:
ones(5)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [76]:
fill(4, 5)

5-element Array{Int64,1}:
 4
 4
 4
 4
 4

In [77]:
fill(0, 5)

5-element Array{Int64,1}:
 0
 0
 0
 0
 0

In [80]:
# vetor de valores aliatorios (quantidade)
randn(5)

5-element Array{Float64,1}:
  1.3473122387285208
 -2.4509651370308396
 -1.5705832803394522
 -1.4489776914850434
  1.531621077656675 

In [81]:
#indexação
#criar o vetor
v = collect(10:10:100)

10-element Array{Int64,1}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [91]:
# ver o ultimo elemento do vetor
v[length(v)]

100

In [92]:
# primeiro elemento do vetor
v[1]

10

In [93]:
# ver o ultimo elemento do vetor
v[end]

100

In [94]:
# ver o penultimo elemento do vetor
v[end-1]

90

In [95]:
# criar um vetor com os ultimos tres elementos do vetor v
h = [v[end-2], v[end-1], v[end]]

3-element Array{Int64,1}:
  80
  90
 100

In [100]:
# mesma coisa que anteriormente, mas de forma mais simples
h = v[[end-2, end-1, end]]

3-element Array{Int64,1}:
  80
  90
 100

In [103]:
# ainda mais simples a mesma operação anterior
h = v[end-2:end]

3-element Array{Int64,1}:
  80
  90
 100

In [104]:
# retirar os valores de v a partir de 2, com step de 2 em 2, até ao fim
g = v[2:2:end]

5-element Array{Int64,1}:
  20
  40
  60
  80
 100